//
//  StockRank.swift
//  TheFellowshipOfAnts
//
//  Created by SeYeong on 2022/08/31.
//

import Foundation

struct StockRank {
    let rank: String
    let logoURL: String
    let companyName: String
    let symbol: String
    let price: String
    let fluctuationRate: String
    let upDown: UpDown
}

extension StockRank {
    static let dummy: [StockRank] =  [
        StockRank(rank: "1",
                  logoURL: "https://companiesmarketcap.com/img/company-logos/64/AAPL.png",
                  companyName: "Apple",
                  symbol: "AAPL",
                  price: "$157.22",
                  fluctuationRate: "1.06%",
                  upDown: UpDown.down),
        StockRank(rank: "2",
                  logoURL: "https://companiesmarketcap.com/img/company-logos/64/MSFT.png",
                  companyName: "Microsoft",
                  symbol: "MSFT",
                  price: "$261.47",
                  fluctuationRate: "0.57%",
                  upDown: UpDown.down),
        StockRank(rank: "3",
                  logoURL: "https://companiesmarketcap.com/img/company-logos/64/GOOG.png",
                  companyName: "Alphabet (Google)",
                  symbol: "GOOG",
                  price: "$109.15",
                  fluctuationRate: "0.69%",
                  upDown: UpDown.down),
        StockRank(rank: "4",
                  logoURL: "https://companiesmarketcap.com/img/company-logos/64/AMZN.png",
                  companyName: "Amazon",
                  symbol: "AMZN",
                  price: "$126.77",
                  fluctuationRate: "1.52%",
                  upDown: UpDown.down),
        StockRank(rank: "5",
                  logoURL: "https://companiesmarketcap.com/img/company-logos/64/TSLA.png",
                  companyName: "Tesla",
                  symbol: "TSLA",
                  price: "$275.61",
                  fluctuationRate: "0.75%",
                  upDown: UpDown.down),
        StockRank(rank: "6",
                  logoURL: "https://companiesmarketcap.com/img/company-logos/64/BRK-B.png",
                  companyName: "Berkshire Hathaway",
                  symbol: "BRK-B",
                  price: "$280.80",
                  fluctuationRate: "1.62%",
                  upDown: UpDown.down),
        StockRank(rank: "7",
                  logoURL: "https://companiesmarketcap.com/img/company-logos/64/UNH.png",
                  companyName: "UnitedHealth",
                  symbol: "UNH",
                  price: "$519.33",
                  fluctuationRate: "0.67%",
                  upDown: UpDown.down),
        StockRank(rank: "8",
                  logoURL: "https://companiesmarketcap.com/img/company-logos/64/META.png",
                  companyName: "Meta Platforms (Facebook)",
                  symbol: "META",
                  price: "$162.93",
                  fluctuationRate: "3.67%",
                  upDown: UpDown.up),
        StockRank(rank: "9",
                  logoURL: "https://companiesmarketcap.com/img/company-logos/64/JNJ.png",
                  companyName: "Johnson & Johnson",
                  symbol: "JNJ",
                  price: "$161.34",
                  fluctuationRate: "0.67%",
                  upDown: UpDown.down),
        StockRank(rank: "10",
                  logoURL: "https://companiesmarketcap.com/img/company-logos/64/V.png",
                  companyName: "Visa",
                  symbol: "V",
                  price: "$198.71",
                  fluctuationRate: "1.33%",
                  upDown: UpDown.down),
        StockRank(rank: "11",
                  logoURL: "https://companiesmarketcap.com/img/company-logos/64/XOM.png",
                  companyName: "Exxon Mobil",
                  symbol: "XOM",
                  price: "$95.59",
                  fluctuationRate: "0.75%",
                  upDown: UpDown.down),
        StockRank(rank: "12",
                  logoURL: "https://companiesmarketcap.com/img/company-logos/64/NVDA.png",
                  companyName: "NVIDIA",
                  symbol: "NVDA",
                  price: "$150.94",
                  fluctuationRate: "2.42%",
                  upDown: UpDown.down),
        StockRank(rank: "13",
                  logoURL: "https://companiesmarketcap.com/img/company-logos/64/WMT.png",
                  companyName: "Walmart",
                  symbol: "WMT",
                  price: "$132.55",
                  fluctuationRate: "0.05%",
                  upDown: UpDown.up),
        StockRank(rank: "14",
                  logoURL: "https://companiesmarketcap.com/img/company-logos/64/JPM.png",
                  companyName: "JPMorgan Chase",
                  symbol: "JPM",
                  price: "$113.73",
                  fluctuationRate: "0.59%",
                  upDown: UpDown.down),
        StockRank(rank: "15",
                  logoURL: "https://companiesmarketcap.com/img/company-logos/64/PG.png",
                  companyName: "Procter & Gamble",
                  symbol: "PG",
                  price: "$137.94",
                  fluctuationRate: "1.60%",
                  upDown: UpDown.down),
        StockRank(rank: "16",
                  logoURL: "https://companiesmarketcap.com/img/company-logos/64/MA.png",
                  companyName: "Mastercard",
                  symbol: "MA",
                  price: "$324.37",
                  fluctuationRate: "1.05%",
                  upDown: UpDown.down),
        StockRank(rank: "17",
                  logoURL: "https://companiesmarketcap.com/img/company-logos/64/CVX.png",
                  companyName: "Chevron",
                  symbol: "CVX",
                  price: "$158.06",
                  fluctuationRate: "1.59%",
                  upDown: UpDown.down),
        StockRank(rank: "18",
                  logoURL: "https://companiesmarketcap.com/img/company-logos/64/HD.png",
                  companyName: "Home Depot",
                  symbol: "HD",
                  price: "$288.42",
                  fluctuationRate: "0.95%",
                  upDown: UpDown.down),
        StockRank(rank: "19",
                  logoURL: "https://companiesmarketcap.com/img/company-logos/64/LLY.png",
                  companyName: "Eli Lilly",
                  symbol: "LLY",
                  price: "$301.23",
                  fluctuationRate: "1.89%",
                  upDown: UpDown.down),
        StockRank(rank: "20",
                  logoURL: "https://companiesmarketcap.com/img/company-logos/64/BAC.png",
                  companyName: "Bank of America",
                  symbol: "BAC",
                  price: "$33.61",
                  fluctuationRate: "1.41%",
                  upDown: UpDown.down)
    ]
}
